# Generated by Django 6.0.1 on 2026-01-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('required_attributes', models.JSONField()),
                ('system_prompt', models.TextField()),
                ('intent_prompt', models.TextField(default="Classify the query into 'general' or 'product_search'.")),
                ('attribute_extraction_prompt', models.TextField(default='Extract attributes from the query.')),
                ('missing_attribute_prompt', models.TextField(default='Ask for missing attributes.')),
                ('product_recommendation_prompt', models.TextField(default='Recommend products based on these results.')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.CharField(max_length=255)),
                ('required_attributes', models.JSONField()),
                ('system_prompt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attributes', models.JSONField()),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
