# Generated by Django 6.0.1 on 2026-01-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('required_attributes', models.JSONField()),
                ('system_prompt', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.AddField(
            model_name='organization',
            name='domain',
            field=models.CharField(default='example.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='required_attributes',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='system_prompt',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='attributes',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
