# Generated by Django 6.0.1 on 2026-01-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botsettings',
            name='missing_attribute_prompt',
        ),
        migrations.RemoveField(
            model_name='botsettings',
            name='product_recommendation_prompt',
        ),
    ]
