# Generated by Django 6.0.1 on 2026-01-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_botsettings_remove_products_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
