# Generated by Django 6.0.1 on 2026-01-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_products_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
