# Generated by Django 6.0.1 on 2026-01-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='attribute_extraction_prompt',
            field=models.TextField(default='Extract attributes from the query.'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='intent_prompt',
            field=models.TextField(default="Classify the query into 'general' or 'product_search'."),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='missing_attribute_prompt',
            field=models.TextField(default='Ask for missing attributes.'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='product_recommendation_prompt',
            field=models.TextField(default='Recommend products based on these results.'),
        ),
    ]
