# Generated by Django 6.0.1 on 2026-01-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessages_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='extracted_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='missing_attributes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
